[package]
name = "external"
version = "0.1.0"
edition = "2018"

[dependencies]
ntapi = "0.2"

[dependencies.winapi]
version = "0.3.6"
features = [
	"consoleapi",
	"errhandlingapi",
	"handleapi",
	"memoryapi",
	"processthreadsapi",
	"profileapi",
	"synchapi",
	"tlhelp32",
	"winbase",
	"wingdi",
	"winerror",
	"winuser",
]
